version = 0.1
[default.deploy.parameters]
stack_name = "sam-app-dev"
resolve_s3 = true
s3_prefix = "sam-app-dev"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
